<?php
session_start();
require_once '../config/db_connect.php';

// Check authorization
if (!isset($_SESSION['user_id']) || !in_array($_SESSION['role'], ['admin', 'ceo', 'operator'])) {
    header('Location: ../index.php');
    exit();
}

$userRole = $_SESSION['role'];
?>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Управление контрактами - Kvazar</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="../css/sidebar.css">
    <link rel="stylesheet" href="../css/manage_contracts.css">
</head>
<body>
    <div class="wrapper">
        <?php include '../elements/admin_sidebar.php'; ?>
        
        <div id="content">
            <?php 
            $page_title = 'Управление контрактами';
            include '../elements/admin_navbar.php'; 
            ?>
            
            <div class="content-wrapper">
                <div class="mc-content-wrapper">
                    <div class="page-header">
                        <h2>Управление контрактами</h2>
                    </div>

                    <!-- Search and Filter Section -->
                    <div class="filters-section">
                        <div class="filters-left">
                            <div class="search-box">
                                <input type="text" id="searchInput" placeholder="Поиск контрактов...">
                                <i class="fas fa-search"></i>
                            </div>
                            <div class="filters">
                                <select id="typeFilter">
                                    <option value="">Все типы</option>
                                    <?php
                                    $stmt = $pdo->query("SELECT Type_id, Type_name FROM list_contract_type ORDER BY Type_name");
                                    while ($row = $stmt->fetch()) {
                                        echo "<option value='" . htmlspecialchars($row['Type_id']) . "'>" . 
                                             htmlspecialchars($row['Type_name']) . "</option>";
                                    }
                                    ?>
                                </select>
                                <select id="statusFilter">
                                    <option value="">Все статусы</option>
                                    <?php
                                    $stmt = $pdo->query("SELECT Status_name FROM list_contract_status ORDER BY Status_name");
                                    while ($row = $stmt->fetch()) {
                                        echo "<option value='" . htmlspecialchars($row['Status_name']) . "'>" . 
                                             htmlspecialchars($row['Status_name']) . "</option>";
                                    }
                                    ?>
                                </select>
                                <div class="date-range">
                                    <input type="date" id="dateFrom" placeholder="От">
                                    <input type="date" id="dateTo" placeholder="До">
                                </div>
                            </div>
                        </div>
                        <div class="filters-right">
                            <button id="downloadContracts" class="btn-secondary" title="Скачать данные">
                                <i class="fas fa-download"></i>
                            </button>
                        </div>
                    </div>

                    <!-- Tabs -->
                    <div class="tabs">
                        <div class="tabs-left">
                            <button class="tab-btn active" data-tab="client">Контракты клиентов</button>
                            <button class="tab-btn" data-tab="courier">Контракты перевозчиков</button>
                            <button class="tab-btn" data-tab="agent">Контракты подрядчиков</button>
                        </div>
                    </div>

                    <!-- Contracts Table -->
                    <div class="table-container" id="tableContainer">
                        <div class="scroll-indicator" id="scrollIndicator">Прокрутка...</div>
                        <table id="contractsTable">
                            <thead>
                                <tr id="tableHeaders">
                                    <!-- Headers will be generated by JavaScript -->
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Data will be loaded here via JavaScript -->
                            </tbody>
                        </table>
                    </div>

                    <!-- Pagination -->
                    <div id="paginationContainer" class="pagination-container"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- Column Settings Modal -->
    <div id="columnSettingsModal" class="modal">
        <div class="modal-content">
            <h3>Видимость колонок</h3>
            <div id="columnCheckboxes">
                <!-- Checkboxes will be added via JavaScript -->
            </div>
            <div class="modal-buttons">
                <button id="applyColumnSettings" class="btn-primary">Применить</button>
                <button id="cancelColumnSettings" class="btn-secondary">Отмена</button>
            </div>
        </div>
    </div>

    <!-- Password Confirmation Modal -->
    <div id="passwordModal" class="mc-modal">
        <div class="mc-modal-content">
            <span class="mc-close" id="passwordModalClose">&times;</span>
            <h2>Введите пароль для подтверждения действия</h2>
            <form id="passwordForm">
                <input type="hidden" id="actionType" name="action_type">
                <input type="password" id="actionPassword" name="action_password" placeholder="Пароль" required>
                <button type="submit" class="mc-btn-submit">Подтвердить</button>
            </form>
            <div id="passwordError" style="color: red; display: none; margin-top: 10px;"></div>
        </div>
    </div>

    <!-- Status Change Modal -->
    <div id="statusModal" class="modal">
        <div class="modal-content">
            <h3>Изменить статус контракта</h3>
            <div class="status-options">
                <?php
                $stmt = $pdo->query("SELECT Status_name, Status_color FROM list_contract_status ORDER BY Status_name");
                while ($status = $stmt->fetch()) {
                    echo "<button class='status-option' data-status='{$status['Status_name']}' 
                        style='border-color: {$status['Status_color']}'>
                        <span class='status-dot' style='background-color: {$status['Status_color']}'></span>
                        {$status['Status_name']}
                    </button>";
                }
                ?>
            </div>
            <div class="modal-buttons">
                <button id="cancelStatusChange" class="btn-secondary">Отмена</button>
            </div>
        </div>
    </div>

    <!-- File Preview Modal -->
    <div id="filePreviewModal" class="modal">
        <div class="modal-content file-preview-content">
            <span class="close" id="filePreviewClose">&times;</span>
            <h3 id="filePreviewTitle">Просмотр файла</h3>
            <div id="filePreviewContainer">
                <!-- File content will be loaded here -->
            </div>
            <div class="modal-buttons">
                <button id="downloadFileBtn" class="btn-primary">
                    <i class="fas fa-download"></i> Скачать
                </button>
                <button id="closeFilePreview" class="btn-secondary">Закрыть</button>
            </div>
        </div>
    </div>

    <script src="../js/manage_contracts.js"></script>
    <script src="../js/sidebar.js"></script>
</body>
</html> 